import { expect, test } from '@playwright/test'

test('opens the invitation with the supplied static hero image', async ({ page }) => {
  await page.goto('/invite/demo?to=Guest+Name')
  await expect(page.getByRole('button', { name: "Let's Open" })).toBeVisible({ timeout: 10_000 })
  await expect(page.getByText('Guest Name', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: "Let's Open" }).click()
  await expect(page.locator('.opening-cover')).toHaveCount(0)
  await expect(page.locator('main')).not.toHaveAttribute('inert')
  await expect(page.locator('.hero-video')).toHaveCount(0)
  await expect(page.locator('.hero-media--base img')).toHaveAttribute('src', '/images/kv.png')
  await expect(page.locator('.hero-media--foreground img')).toHaveAttribute('src', '/images/kv-transparent.png')
})

test('keeps RSVP, gift, wishes, and gallery interactions local', async ({ page }) => {
  await page.route('https://www.youtube.com/**', route => route.abort())
  await page.goto('/invite/demo?to=Guest+Name')
  await expect(page.locator('.invitation-experience')).toHaveAttribute('data-enhanced', 'true')
  await page.getByRole('button', { name: "Let's Open" }).click()
  await expect(page.locator('.opening-cover')).toHaveCount(0)
  await page.getByRole('button', { name: 'Open navigation' }).click()
  await page.getByRole('button', { name: 'RSVP', exact: true }).click()
  await expect(page.locator('#rsvp')).toBeFocused()
  await page.getByRole('button', { name: 'Send Confirmation' }).click()
  await expect(page.locator('#rsvp-attendance-error')).toBeVisible()
  await page.locator('#rsvp-attendance').selectOption('ATTENDING')
  await expect(page.locator('#rsvp-eventId')).toBeVisible()
  await page.locator('#rsvp-eventId').selectOption('matrimony')
  await page.locator('#rsvp-attendanceCount').selectOption('2')
  await page.getByRole('button', { name: 'Send Confirmation' }).click()
  await expect(page.locator('.rsvp-form .form-status')).toContainText('saved for this preview')

  await page.getByRole('button', { name: 'Next »' }).click()
  await expect(page.locator('#wishes-title').locator('..')).toContainText('Page 2 of 2')

  await page.getByRole('button', { name: 'Click Here' }).click()
  await expect(page.getByRole('dialog', { name: 'Wedding gift' })).toBeVisible()
  await page.getByRole('button', { name: 'SEND', exact: true }).click()
  await expect(page.locator('.gift-form-panel .field-error')).toHaveCount(3)
  await page.locator('#gift-name').fill('Alex')
  await page.locator('#gift-bank').selectOption('preview-a')
  await page.locator('#gift-amount').fill('50000')
  await page.getByRole('button', { name: 'SEND', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Wedding gift' })).toContainText('Preview confirmation recorded')
  await page.getByRole('button', { name: 'Close gift panel' }).click()

  const firstPhoto = page.getByRole('button', { name: /Open photo 1 of 16/ })
  await firstPhoto.click()
  await expect(page.getByRole('dialog', { name: 'Photo gallery' })).toContainText('1 / 16')
  await page.getByRole('button', { name: 'Next photo' }).click()
  await expect(page.getByRole('dialog', { name: 'Photo gallery' })).toContainText('2 / 16')
  await page.keyboard.press('Escape')
  await expect(firstPhoto).toBeFocused()

  const calendarDownload = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Add to Calendar' }).click()
  expect((await calendarDownload).suggestedFilename()).toBe('bayu-hilwa-wedding.ics')
  await page.locator('.video-frame').hover({ position: { x: 110, y: 110 } })
  await expect(page.locator('.video-pointer')).toHaveClass(/is-visible/)
  await page.getByRole('button', { name: 'PLAY', exact: true }).click()
  await expect(page.locator('.video-feature iframe')).toHaveAttribute('src', /youtube\.com\/embed\/BNQj5Muhss4/)
})

test('preserves route boundaries and responsive width', async ({ page }) => {
  await page.goto('/?to=Guest+Name')
  expect(new URL(page.url()).searchParams.get('to')).toBe('Guest Name')
  await expect(page).toHaveURL(/\/invite\/demo/)
  await page.goto('/invite/protected')
  await expect(page.locator('body')).not.toContainText('Jl. Taman Palem Lestari Barat')
  await page.goto('/invite/unavailable')
  await expect(page.locator('body')).not.toContainText('Jl. Taman Palem Lestari Barat')
  await page.goto('/invite/demo?qa=static')
  for (const [width, height] of [[320, 720], [390, 844], [767, 900], [768, 1024], [1024, 768], [1025, 768], [1680, 939]] as const) {
    await page.setViewportSize({ width, height })
    expect(await page.evaluate(() => document.documentElement.scrollWidth), `overflow at ${width}px`).toBeLessThanOrEqual(width)
  }
})

test('reverses the portrait aperture and settles it for reduced motion', async ({ page }) => {
  await page.goto('/invite/demo?to=Guest+Name')
  await page.getByRole('button', { name: "Let's Open" }).click()
  await expect(page.locator('.opening-cover')).toHaveCount(0)
  const portrait = page.locator('.profile-portrait').first()
  await portrait.evaluate(element => window.scrollTo({ top: window.scrollY + element.getBoundingClientRect().top - 417, behavior: 'instant' }))
  const inset = () => portrait.evaluate(element => Number(element.style.clipPath.match(/inset\(([\d.]+)%/)?.[1] || 0))
  await expect.poll(inset).toBeGreaterThan(4)
  await expect.poll(inset).toBeLessThan(4.5)
  await expect(portrait.locator('img')).toHaveAttribute('style', /translateY\(-7[56]/)

  await page.evaluate(() => window.scrollBy({ top: -188, behavior: 'instant' }))
  await expect.poll(inset).toBeGreaterThan(10)
  await expect.poll(inset).toBeLessThan(10.5)

  const story = page.locator('.story-intro-frame')
  await story.evaluate(element => element.scrollIntoView({ behavior: 'instant', block: 'center' }))
  const initialStoryImage = await story.locator('.story-slide img').last().getAttribute('src')
  await expect.poll(() => story.locator('.story-slide img').last().getAttribute('src'), { timeout: 9_000 }).not.toBe(initialStoryImage)
  await expect(story.locator('.story-slide img').last()).toBeVisible()

  await page.emulateMedia({ reducedMotion: 'reduce' })
  await expect.poll(() => portrait.evaluate(element => element.style.clipPath)).toBe('none')
  await expect.poll(() => portrait.locator('img').evaluate(element => (element as HTMLElement).style.transform)).toBe('')
  await page.goto('/invite/demo?to=Guest+Name')
  await expect(page.getByRole('button', { name: "Let's Open" })).toBeVisible({ timeout: 1_500 })
})
